In [1]:
import numpy as np

In [3]:
x=np.array(['a',40,67,57,90])
print(x)
print(type(x))
print(x.dtype)

['a' '40' '67' '57' '90']
<class 'numpy.ndarray'>
<U11


In [4]:
a2=np.array([[20,40],[30,60]])
print(a2)
print(type(a2))

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>


In [5]:
a= np.array([10,20,30,40])
b=a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [7]:
c=np.arange(3,20)
print(c)
type(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [8]:
d = np.array([1.3467,3.10987,4.91236])
np.around(d,2)

array([1.35, 3.11, 4.91])

In [9]:
print(np.sqrt(d))

[1.16047404 1.76348235 2.21638444]


In [12]:
a1=np.array([[3,4,5,8],[7,2,8,np.NAN]])
print(a1)
a1.dtype


[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [13]:
a2=np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [15]:
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))
print(a2)
print(np.mean(a2, axis=1))
print(np.mean(a2, axis=0))

[13 26 22]
[14 19 28]
[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[4.33333333 8.66666667 7.33333333]
[4.66666667 6.33333333 9.33333333]


In [16]:
a3=np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [17]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
c=np.matmul(A,B)

In [18]:
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [23]:
a4=np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
print(a4)
a4[:,1:]

[[ 3  4  5]
 [ 7  2  8]
 [ 9  1  6]
 [10  9 18]]


array([[ 4,  5],
       [ 2,  8],
       [ 1,  6],
       [ 9, 18]])

In [25]:
a4[1:3,:2]

array([[7, 2],
       [9, 1]])